/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_danielalvarado;

import java.awt.Color;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author dalva
 */
public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CrearPersona = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_N = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt_Apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        js_Edad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jr_M = new javax.swing.JRadioButton();
        jr_F = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jt_Vocacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jr_TY = new javax.swing.JRadioButton();
        jr_Tn = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jr_CY = new javax.swing.JRadioButton();
        jr_CN = new javax.swing.JRadioButton();
        jg_GuardarPersona = new javax.swing.JButton();
        jg_Sexo = new javax.swing.ButtonGroup();
        bg_Titulo = new javax.swing.ButtonGroup();
        bg_Covid = new javax.swing.ButtonGroup();
        jd_CrearPais = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jt_NombreP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jd_FechaFundacion = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jt_Himno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jb_Color = new javax.swing.JButton();
        jb_GuardarPais = new javax.swing.JButton();
        popup_AgregarPersona = new javax.swing.JPopupMenu();
        popup_Agregar = new javax.swing.JMenuItem();
        popup_ModArbol = new javax.swing.JPopupMenu();
        jm_AgregarP = new javax.swing.JMenuItem();
        jm_Modificar = new javax.swing.JMenuItem();
        jm_Eliminar = new javax.swing.JMenuItem();
        popup_ModPersona = new javax.swing.JPopupMenu();
        jp_EliminarPer = new javax.swing.JMenuItem();
        jp_ModPer = new javax.swing.JMenuItem();
        jp_ExpatriarPer = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_Masculino = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_Femenino = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_Paises = new javax.swing.JList<>();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_Paises = new javax.swing.JTree();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_PaisesCovid = new javax.swing.JTree();
        jb_ActualizarArbol = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jm_AgregarPersona = new javax.swing.JMenuItem();
        jm_AgregarPais = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Persona");

        jLabel2.setText("Nacionalidad");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Edad");

        js_Edad.setModel(new javax.swing.SpinnerNumberModel(20, 0, 100, 1));

        jLabel6.setText("Genero");

        jg_Sexo.add(jr_M);
        jr_M.setText("M");

        jg_Sexo.add(jr_F);
        jr_F.setText("F");

        jLabel7.setText("Vocacion");

        jLabel8.setText("Titulo ");

        bg_Titulo.add(jr_TY);
        jr_TY.setText("Si");

        bg_Titulo.add(jr_Tn);
        jr_Tn.setText("No");

        jLabel9.setText("Tiene Covid?");

        bg_Covid.add(jr_CY);
        jr_CY.setText("Si");

        bg_Covid.add(jr_CN);
        jr_CN.setText("No");

        jg_GuardarPersona.setText("Agregar");
        jg_GuardarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jg_GuardarPersonaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearPersonaLayout = new javax.swing.GroupLayout(jd_CrearPersona.getContentPane());
        jd_CrearPersona.getContentPane().setLayout(jd_CrearPersonaLayout);
        jd_CrearPersonaLayout.setHorizontalGroup(
            jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jt_N)
                                    .addComponent(jt_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                                .addGap(86, 86, 86)
                                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                                .addComponent(jr_TY)
                                .addGap(18, 18, 18)
                                .addComponent(jr_Tn)
                                .addGap(149, 149, 149)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CrearPersonaLayout.createSequentialGroup()
                                .addComponent(jr_M)
                                .addGap(18, 18, 18)
                                .addComponent(jr_F)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jt_Apellido)
                                .addComponent(js_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jt_Vocacion, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                            .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                                .addComponent(jr_CY)
                                .addGap(18, 18, 18)
                                .addComponent(jr_CN))))
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jg_GuardarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jd_CrearPersonaLayout.setVerticalGroup(
            jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jt_N, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(js_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jr_M)
                                .addComponent(jr_F))))
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_Vocacion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(42, 42, 42)
                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jr_TY)
                    .addComponent(jr_Tn)
                    .addComponent(jLabel9)
                    .addComponent(jr_CY)
                    .addComponent(jr_CN))
                .addGap(64, 64, 64)
                .addComponent(jg_GuardarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Crear Un Pais");

        jLabel11.setText("Nombre");

        jLabel12.setText("Fecha Fundacion");

        jLabel13.setText("Himno");

        jLabel14.setText("Color Bandera");

        jb_Color.setBackground(new java.awt.Color(255, 0, 0));
        jb_Color.setText("Color");
        jb_Color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ColorMouseClicked(evt);
            }
        });

        jb_GuardarPais.setText("Guardar");
        jb_GuardarPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_GuardarPaisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearPaisLayout = new javax.swing.GroupLayout(jd_CrearPais.getContentPane());
        jd_CrearPais.getContentPane().setLayout(jd_CrearPaisLayout);
        jd_CrearPaisLayout.setHorizontalGroup(
            jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearPaisLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_NombreP)
                    .addComponent(jt_Himno, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearPaisLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jd_FechaFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Color)))
                    .addGroup(jd_CrearPaisLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_GuardarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jd_CrearPaisLayout.setVerticalGroup(
            jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearPaisLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jt_NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addGroup(jd_CrearPaisLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jd_FechaFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jt_Himno, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jb_Color))
                .addGap(89, 89, 89)
                .addComponent(jb_GuardarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        popup_Agregar.setText("Agregar persona a pais");
        popup_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_AgregarActionPerformed(evt);
            }
        });
        popup_AgregarPersona.add(popup_Agregar);

        jm_AgregarP.setText("Agregar Persona");
        popup_ModArbol.add(jm_AgregarP);

        jm_Modificar.setText("jMenuItem2");
        jm_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ModificarActionPerformed(evt);
            }
        });
        popup_ModArbol.add(jm_Modificar);

        jm_Eliminar.setText("jMenuItem3");
        jm_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_EliminarActionPerformed(evt);
            }
        });
        popup_ModArbol.add(jm_Eliminar);

        jp_EliminarPer.setText("Eliminar Persona");
        jp_EliminarPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp_EliminarPerActionPerformed(evt);
            }
        });
        popup_ModPersona.add(jp_EliminarPer);

        jp_ModPer.setText("Modificar Persona");
        jp_ModPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp_ModPerActionPerformed(evt);
            }
        });
        popup_ModPersona.add(jp_ModPer);

        jp_ExpatriarPer.setText("Expatriar Persona");
        jp_ExpatriarPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp_ExpatriarPerActionPerformed(evt);
            }
        });
        popup_ModPersona.add(jp_ExpatriarPer);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_Masculino.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_Masculino);

        jLabel15.setText("Personas Masculinas");

        jLabel16.setText("Personas Femeninas");

        jl_Femenino.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_Femenino);

        jLabel17.setText("Paises");

        jl_Paises.setModel(new DefaultListModel());
        jl_Paises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_PaisesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jl_Paises);

        jLabel18.setText("Arbol");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Paises");
        jt_Paises.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_Paises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_PaisesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jt_Paises);

        jLabel19.setText("Arbol Covid");

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Paises");
        jt_PaisesCovid.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(jt_PaisesCovid);

        jb_ActualizarArbol.setText("----->");

        jMenu3.setText("Herramientas");

        jm_AgregarPersona.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jm_AgregarPersona.setText("Agregar Persona");
        jm_AgregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_AgregarPersonaActionPerformed(evt);
            }
        });
        jMenu3.add(jm_AgregarPersona);

        jm_AgregarPais.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jm_AgregarPais.setText("Agregar Pais");
        jm_AgregarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_AgregarPaisActionPerformed(evt);
            }
        });
        jMenu3.add(jm_AgregarPais);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel15)
                .addGap(202, 202, 202)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jb_ActualizarArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(315, 315, 315))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_ActualizarArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_AgregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_AgregarPersonaActionPerformed

        jd_CrearPersona.setModal(true);
        jd_CrearPersona.pack();
        jd_CrearPersona.setLocationRelativeTo(jm_AgregarPersona);
        jd_CrearPersona.setVisible(true);

    }//GEN-LAST:event_jm_AgregarPersonaActionPerformed

    private void jm_AgregarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_AgregarPaisActionPerformed
        jd_CrearPais.setModal(true);
        jd_CrearPais.pack();
        jd_CrearPais.setLocationRelativeTo(jm_AgregarPais);
        jd_CrearPais.setVisible(true);
    }//GEN-LAST:event_jm_AgregarPaisActionPerformed

    private void jg_GuardarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jg_GuardarPersonaMouseClicked

        if (jt_Nombre.getText().equals("") || jt_Apellido.getText().equals("") || js_Edad.getValue().equals("0")
                || jt_Vocacion.getText().equals("") || jt_N.getText().equals("")) {
            JOptionPane.showMessageDialog(jd_CrearPersona, "No puede dejar las casillas vacias!");
        } else {
            String genero = "";
            boolean titulo = false;
            boolean covid = false;

            if (jr_M.isSelected()) {
                genero = "Masculino";
            } else if (jr_F.isSelected()) {
                genero = "Femenino";
            }

            if (jr_TY.isSelected()) {
                titulo = true;
            } else {
                titulo = false;
            }

            if (jr_CY.isSelected()) {
                covid = true;
            } else {
                covid = false;
            }

            Persona p = new Persona(
                    jt_N.getText(),
                    jt_Nombre.getText(),
                    jt_Apellido.getText(),
                    (int) js_Edad.getValue(),
                    genero,
                    jt_Vocacion.getText(),
                    titulo,
                    covid
            );

            if (genero.equals("Masculino")) {
                DefaultListModel modelo = (DefaultListModel) jl_Masculino.getModel();

                modelo.addElement(p);

                jl_Masculino.setModel(modelo);
            } else if (genero.equals("Femenino")) {
                DefaultListModel fModelo = (DefaultListModel) jl_Femenino.getModel();

                fModelo.addElement(p);

                jl_Femenino.setModel(fModelo);
            }

            jt_N.setText("");
            jt_Nombre.setText("");
            jt_Apellido.setText("");
            js_Edad.setValue(20);
            jr_M.setSelected(true);
            jr_CY.setSelected(true);
            jr_TY.setSelected(true);
            jt_Vocacion.setText("");

        }
    }//GEN-LAST:event_jg_GuardarPersonaMouseClicked

    private void jb_GuardarPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_GuardarPaisMouseClicked

        if (jt_NombreP.getText().equals("") || jt_Himno.getText().equals("")) {
            JOptionPane.showMessageDialog(jd_CrearPais, "No puede dejar las casillas vacias!");
        } else {

            Pais p = new Pais(
                    jt_NombreP.getText(),
                    jd_FechaFundacion.getDate(),
                    jt_Himno.getText(),
                    jb_Color.getBackground()
            );

            DefaultListModel modelo = (DefaultListModel) jl_Paises.getModel();

            modelo.addElement(p);

            jl_Paises.setModel(modelo);

            jt_NombreP.setText("");
            jd_FechaFundacion.setDate(new Date());
            jt_Himno.setText("");
            jb_Color.setBackground(Color.red);
        }
    }//GEN-LAST:event_jb_GuardarPaisMouseClicked

    private void jb_ColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ColorMouseClicked

        jb_Color.setBackground(JColorChooser.showDialog(jd_CrearPais, "Elija un color: ", Color.yellow));
    }//GEN-LAST:event_jb_ColorMouseClicked

    private void popup_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_AgregarActionPerformed
        DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_Paises.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
        DefaultListModel modeloM = (DefaultListModel) jl_Masculino.getModel();
        DefaultListModel modeloP = (DefaultListModel) jl_Paises.getModel();
        DefaultListModel modeloF = (DefaultListModel) jl_Femenino.getModel();

        int n = Integer.parseInt(JOptionPane.showInputDialog(jl_Paises, "Ingrese de que lista va a agregar 1 =(Femenino) o 2 = (Masculino)"));

        int num = Integer.parseInt(JOptionPane.showInputDialog(jl_Paises, "Ingrese el indice: "));
        Persona per = new Persona();

        if (n == 1) {
            while (num < 0 || num > modeloF.getSize()) {
                num = Integer.parseInt(JOptionPane.showInputDialog(jl_Paises, "Ingrese el indice: "));
            }

            per = (Persona) modeloF.getElementAt(num);

        } else if (n == 2) {
            while (num < 0 || num > modeloM.getSize()) {
                num = Integer.parseInt(JOptionPane.showInputDialog(jl_Paises, "Ingrese el indice: "));
            }

            per = (Persona) modeloM.getElementAt(num);
        }

        int in = jl_Paises.getSelectedIndex();
        Pais p = (Pais) modeloP.getElementAt(in);
        String pais = p.getNombre();
        pais = pais.trim();
        boolean flag = false;
        boolean flag2 = false;
        boolean flagM = true;

        

        if (p.getNombre().equals(per.getNacionalidad())) {

            int centinela = 1;
            int centi2 = 2;
            

            for (int i = 0; i < raiz.getChildCount(); i++) {
                DefaultMutableTreeNode nodo_Pais = (DefaultMutableTreeNode) raiz.getChildAt(i);
                
                flag = true;

                if (nodo_Pais.toString().equals(pais)) {

                    for (int j = 0; j < nodo_Pais.getChildCount(); j++) {
                        DefaultMutableTreeNode nodo_Sexo = (DefaultMutableTreeNode) nodo_Pais.getChildAt(j);

                        if (nodo_Sexo.toString().equals(per.getGenero())) {
                            flag2 = true;
                            DefaultMutableTreeNode nodo_Persona = new DefaultMutableTreeNode(per);

                            nodo_Sexo.add(nodo_Persona);
                            nodo_Pais.add(nodo_Sexo);
                            raiz.add(nodo_Pais);

                            flagM = false;
                           
                        }

                        if (flag2 == false) {
                            centi2 = -2;
                        }

                    }

                } else {
                    centinela = -1;
                }

            }

            if (flag == false) {
                centinela = -1;
            }

            if (flagM) {

                if (centinela == -1) {

                    DefaultMutableTreeNode nodo_c = new DefaultMutableTreeNode(p);
                    DefaultMutableTreeNode nodo_sexo = new DefaultMutableTreeNode(per.getGenero());
                    DefaultMutableTreeNode nodo_per = new DefaultMutableTreeNode(per);

                    nodo_sexo.add(nodo_per);
                    nodo_c.add(nodo_sexo);
                    raiz.add(nodo_c);
                   
                    modeloArbol.reload();

                }
                if (centi2 == -2) {
                  
                    for (int i = 0; i < raiz.getChildCount(); i++) {
                        DefaultMutableTreeNode nacionalidad = (DefaultMutableTreeNode) raiz.getChildAt(i);

                        if (nacionalidad.toString().equals(per.getNacionalidad())) {

                            DefaultMutableTreeNode genero = new DefaultMutableTreeNode(per.getGenero());
                            DefaultMutableTreeNode persona = new DefaultMutableTreeNode(per);
                            genero.add(persona);
                            nacionalidad.add(genero);
                            raiz.add(nacionalidad);
                           
                            modeloArbol.reload();

                        }

                    }
                }

                modeloArbol.reload();
               
            }
        } else {
            JOptionPane.showMessageDialog(jl_Paises, "Las nacionalidades no concuerdan!!");
        }

    }//GEN-LAST:event_popup_AgregarActionPerformed

    private void jl_PaisesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_PaisesMouseClicked
        if (jl_Paises.getSelectedIndex() >= 0) {

            if (evt.isMetaDown()) {
                popup_AgregarPersona.show(jl_Paises, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_PaisesMouseClicked

    private void jm_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ModificarActionPerformed
        DefaultTreeModel modelo = (DefaultTreeModel) jt_Paises.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();

        String himno = JOptionPane.showInputDialog(jt_Paises, "Ingrese un nuevo himno para el pais: ");

        paisSeleccionado.setNombreHimno(himno);

        JOptionPane.showMessageDialog(jt_Paises, "Se cambio el himno del pais");

        modelo.reload();

    }//GEN-LAST:event_jm_ModificarActionPerformed

    private void jm_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_EliminarActionPerformed
        DefaultTreeModel modelo = (DefaultTreeModel) jt_Paises.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();

        raiz.remove(nodo_Seleccionado);

        JOptionPane.showMessageDialog(jt_Paises, "El nodo ha sido eliminado");


    }//GEN-LAST:event_jm_EliminarActionPerformed

    private void jp_EliminarPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp_EliminarPerActionPerformed

        DefaultTreeModel modelo = (DefaultTreeModel) jt_Paises.getModel();

        modelo.removeNodeFromParent(nodo_Seleccionado);

        JOptionPane.showMessageDialog(jt_Paises, "Se elimino la persona correctamente");
    }//GEN-LAST:event_jp_EliminarPerActionPerformed

    private void jp_ExpatriarPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp_ExpatriarPerActionPerformed
        DefaultTreeModel modelo = (DefaultTreeModel) jt_Paises.getModel();

        modelo.removeNodeFromParent(nodo_Seleccionado);

        if (personaSeleccionada.getGenero().equals("Masculino")) {
            DefaultListModel mod = (DefaultListModel) jl_Masculino.getModel();

            mod.addElement(personaSeleccionada);
        } else if (personaSeleccionada.getGenero().equals("Femenino")) {
            DefaultListModel modf = (DefaultListModel) jl_Femenino.getModel();

            modf.addElement(personaSeleccionada);

            JOptionPane.showMessageDialog(jt_Paises, "Se expatrio correctamente a la persona");
        }
    }//GEN-LAST:event_jp_ExpatriarPerActionPerformed

    private void jp_ModPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp_ModPerActionPerformed
        DefaultTreeModel modelo = (DefaultTreeModel) jt_Paises.getModel();

        personaSeleccionada.setNombre(JOptionPane.showInputDialog(jt_Paises, "Ingrese un nuevo nombre: "));

        JOptionPane.showMessageDialog(jt_Paises, "Se modifico el nombre de la persona");

        modelo.reload();
    }//GEN-LAST:event_jp_ModPerActionPerformed

    private void jt_PaisesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_PaisesMouseClicked
        if (evt.isMetaDown()) {

            int row = jt_Paises.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_Paises.setSelectionRow(row);

            Object o = jt_Paises.getSelectionPath().getLastPathComponent();

            if (nodo_Seleccionado.getUserObject() instanceof Pais) {

                popup_ModArbol.show(jt_Paises, evt.getX(), evt.getX());
                nodo_Seleccionado = (DefaultMutableTreeNode) o;
                paisSeleccionado = (Pais) o;
                
            } else if (nodo_Seleccionado.getUserObject() instanceof Persona) {
                popup_ModPersona.show(jt_Paises, evt.getX(), evt.getY());
                nodo_Seleccionado = (DefaultMutableTreeNode) o;
                personaSeleccionada = (Persona) o;
            }
        }
    }//GEN-LAST:event_jt_PaisesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_Covid;
    private javax.swing.ButtonGroup bg_Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jb_ActualizarArbol;
    private javax.swing.JButton jb_Color;
    private javax.swing.JButton jb_GuardarPais;
    private javax.swing.JDialog jd_CrearPais;
    private javax.swing.JDialog jd_CrearPersona;
    private com.toedter.calendar.JDateChooser jd_FechaFundacion;
    private javax.swing.JButton jg_GuardarPersona;
    private javax.swing.ButtonGroup jg_Sexo;
    private javax.swing.JList<String> jl_Femenino;
    private javax.swing.JList<String> jl_Masculino;
    private javax.swing.JList<String> jl_Paises;
    private javax.swing.JMenuItem jm_AgregarP;
    private javax.swing.JMenuItem jm_AgregarPais;
    private javax.swing.JMenuItem jm_AgregarPersona;
    private javax.swing.JMenuItem jm_Eliminar;
    private javax.swing.JMenuItem jm_Modificar;
    private javax.swing.JMenuItem jp_EliminarPer;
    private javax.swing.JMenuItem jp_ExpatriarPer;
    private javax.swing.JMenuItem jp_ModPer;
    private javax.swing.JRadioButton jr_CN;
    private javax.swing.JRadioButton jr_CY;
    private javax.swing.JRadioButton jr_F;
    private javax.swing.JRadioButton jr_M;
    private javax.swing.JRadioButton jr_TY;
    private javax.swing.JRadioButton jr_Tn;
    private javax.swing.JSpinner js_Edad;
    private javax.swing.JTextField jt_Apellido;
    private javax.swing.JTextField jt_Himno;
    private javax.swing.JTextField jt_N;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_NombreP;
    private javax.swing.JTree jt_Paises;
    private javax.swing.JTree jt_PaisesCovid;
    private javax.swing.JTextField jt_Vocacion;
    private javax.swing.JMenuItem popup_Agregar;
    private javax.swing.JPopupMenu popup_AgregarPersona;
    private javax.swing.JPopupMenu popup_ModArbol;
    private javax.swing.JPopupMenu popup_ModPersona;
    // End of variables declaration//GEN-END:variables

    DefaultMutableTreeNode nodo_Seleccionado;
    Pais paisSeleccionado;
    Persona personaSeleccionada;

}
