/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_danielalvarado;

/**
 *
 * @author dalva
 */
public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CrearPersona = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_N = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt_Apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        js_Edad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jr_M = new javax.swing.JRadioButton();
        jr_F = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jt_Vocacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jr_TY = new javax.swing.JRadioButton();
        jr_Tn = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jr_CY = new javax.swing.JRadioButton();
        jr_CN = new javax.swing.JRadioButton();
        jg_GuardarPersona = new javax.swing.JButton();
        jg_Sexo = new javax.swing.ButtonGroup();
        bg_Titulo = new javax.swing.ButtonGroup();
        bg_Covid = new javax.swing.ButtonGroup();
        jd_CrearPais = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jt_NombreP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jd_FechaFundacion = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jt_Himno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jb_Color = new javax.swing.JButton();
        jb_GuardarPais = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jm_AgregarPersona = new javax.swing.JMenuItem();
        jm_AgregarPais = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Persona");

        jLabel2.setText("Nacionalidad");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Edad");

        js_Edad.setModel(new javax.swing.SpinnerNumberModel(20, 0, 100, 1));

        jLabel6.setText("Genero");

        jg_Sexo.add(jr_M);
        jr_M.setText("M");

        jg_Sexo.add(jr_F);
        jr_F.setText("F");

        jLabel7.setText("Vocacion");

        jLabel8.setText("Titulo ");

        bg_Titulo.add(jr_TY);
        jr_TY.setText("Si");

        bg_Titulo.add(jr_Tn);
        jr_Tn.setText("No");

        jLabel9.setText("Tiene Covid?");

        bg_Covid.add(jr_CY);
        jr_CY.setText("Si");

        bg_Covid.add(jr_CN);
        jr_CN.setText("No");

        jg_GuardarPersona.setText("Agregar");

        javax.swing.GroupLayout jd_CrearPersonaLayout = new javax.swing.GroupLayout(jd_CrearPersona.getContentPane());
        jd_CrearPersona.getContentPane().setLayout(jd_CrearPersonaLayout);
        jd_CrearPersonaLayout.setHorizontalGroup(
            jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jt_N)
                                    .addComponent(jt_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                                .addGap(86, 86, 86)
                                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                                .addComponent(jr_TY)
                                .addGap(18, 18, 18)
                                .addComponent(jr_Tn)
                                .addGap(149, 149, 149)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CrearPersonaLayout.createSequentialGroup()
                                .addComponent(jr_M)
                                .addGap(18, 18, 18)
                                .addComponent(jr_F)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jt_Apellido)
                                .addComponent(js_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jt_Vocacion, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                            .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                                .addComponent(jr_CY)
                                .addGap(18, 18, 18)
                                .addComponent(jr_CN))))
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jg_GuardarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jd_CrearPersonaLayout.setVerticalGroup(
            jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jt_N, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(js_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jr_M)
                                .addComponent(jr_F))))
                    .addGroup(jd_CrearPersonaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_Vocacion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(42, 42, 42)
                .addGroup(jd_CrearPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jr_TY)
                    .addComponent(jr_Tn)
                    .addComponent(jLabel9)
                    .addComponent(jr_CY)
                    .addComponent(jr_CN))
                .addGap(65, 65, 65)
                .addComponent(jg_GuardarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Crear Un Pais");

        jLabel11.setText("Nombre");

        jLabel12.setText("Fecha Fundacion");

        jLabel13.setText("Himon");

        jLabel14.setText("Color Bandera");

        jb_Color.setBackground(new java.awt.Color(255, 0, 0));
        jb_Color.setText("Color");

        jb_GuardarPais.setText("Guardar");

        javax.swing.GroupLayout jd_CrearPaisLayout = new javax.swing.GroupLayout(jd_CrearPais.getContentPane());
        jd_CrearPais.getContentPane().setLayout(jd_CrearPaisLayout);
        jd_CrearPaisLayout.setHorizontalGroup(
            jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearPaisLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_NombreP)
                    .addComponent(jt_Himno, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearPaisLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jd_FechaFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Color)))
                    .addGroup(jd_CrearPaisLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_GuardarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jd_CrearPaisLayout.setVerticalGroup(
            jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearPaisLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jt_NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addGroup(jd_CrearPaisLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jd_FechaFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jd_CrearPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jt_Himno, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jb_Color))
                .addGap(89, 89, 89)
                .addComponent(jb_GuardarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Herramientas");

        jm_AgregarPersona.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jm_AgregarPersona.setText("Agregar Persona");
        jm_AgregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_AgregarPersonaActionPerformed(evt);
            }
        });
        jMenu3.add(jm_AgregarPersona);

        jm_AgregarPais.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jm_AgregarPais.setText("Agregar Pais");
        jMenu3.add(jm_AgregarPais);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_AgregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_AgregarPersonaActionPerformed
       
        jd_CrearPersona.setModal(true);
        jd_CrearPersona.pack();
        jd_CrearPersona.setLocationRelativeTo(jm_AgregarPersona);
        jd_CrearPersona.setVisible(true);
        
    }//GEN-LAST:event_jm_AgregarPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_Covid;
    private javax.swing.ButtonGroup bg_Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jb_Color;
    private javax.swing.JButton jb_GuardarPais;
    private javax.swing.JDialog jd_CrearPais;
    private javax.swing.JDialog jd_CrearPersona;
    private com.toedter.calendar.JDateChooser jd_FechaFundacion;
    private javax.swing.JButton jg_GuardarPersona;
    private javax.swing.ButtonGroup jg_Sexo;
    private javax.swing.JMenuItem jm_AgregarPais;
    private javax.swing.JMenuItem jm_AgregarPersona;
    private javax.swing.JRadioButton jr_CN;
    private javax.swing.JRadioButton jr_CY;
    private javax.swing.JRadioButton jr_F;
    private javax.swing.JRadioButton jr_M;
    private javax.swing.JRadioButton jr_TY;
    private javax.swing.JRadioButton jr_Tn;
    private javax.swing.JSpinner js_Edad;
    private javax.swing.JTextField jt_Apellido;
    private javax.swing.JTextField jt_Himno;
    private javax.swing.JTextField jt_N;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_NombreP;
    private javax.swing.JTextField jt_Vocacion;
    // End of variables declaration//GEN-END:variables
}
